config/urls.py
from django.conf import settings
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from core.sitemap_list import sitemaps

handler400 = 'sections.views.handler400'
handler403 = 'sections.views.handler403'
handler404 = 'sections.views.handler404'
handler500 = 'sections.views.handler500'

urlpatterns = [
    path('adminp/', admin.site.urls),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    path('', include('sections.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns \
      + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
      + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    CountryDetailView, CountryListView,
    ContinentDetailView, ContinentListView,
    WorldDetailView,)

template_base = 'lte/'

urlpatterns = [
    # path('country/', CountryListView.as_view(
    #     template_name=template_base+'places/'+'country-list.html'
    # ), name='country-list'),

    path('world/', WorldDetailView.as_view(
        template_name=template_base+'places/'+'world-detail.html'
    ), name='world-detail'),

    path('<slug:slug>/',
         CountryDetailView.as_view(
             template_name=template_base+'places/'+'country-detail.html'
         ), name='country-detail'),
]

stats/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    CountryPopulationDetailView,
    WorldPopulationDetailView)

template_base = 'lte/'

urlpatterns = [
    path('world/population/growth-rate/',
         WorldPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'world-growth-rate-detail.html'
         ), name='world-growth-rate-detail'),
    path('world/population/density/',
         WorldPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'world-density-detail.html'
         ), name='world-density-detail'),
    path('world/population/fertility_rate/',
         WorldPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'world-fertility-detail.html'
         ), name='world-fertility-detail'),
    path('world/population/median_age/',
         WorldPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'world-median-age-detail.html'
         ), name='world-median-age-detail'),
    path('world/population/',
         WorldPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'world-population-detail.html'
         ), name='world-population-detail'),


    path('<str:country_slug>/population/growth-rate/',
         CountryPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'country-growth-rate-detail.html'
         ), name='country-growth-rate-detail'),
    path('<str:country_slug>/population/density/',
         CountryPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'country-density-detail.html'
         ), name='country-density-detail'),
    path('<str:country_slug>/population/fertility_rate/',
         CountryPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'country-fertility-detail.html'
         ), name='country-fertility-detail'),
    path('<str:country_slug>/population/median_age/',
         CountryPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'country-median-age-detail.html'
         ), name='country-median-age-detail'),
    path('<str:country_slug>/population/',
         CountryPopulationDetailView.as_view(
             template_name=template_base+'stats/'+'country-population-detail.html'
         ), name='country-population-detail'),
]

accounts/models/base.py
"""Custom User model and related models"""

from django.contrib.auth.models import (
    AbstractUser, Group as DjangoBaseGroup)
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.utils import (
    get_extension, random_chars)


def user_directory_path(instance, filename):
    file_and_ext = get_extension(filename)
    return f'users/{instance.id}/{file_and_ext[0].lower()} \
        -{random_chars(3)}{file_and_ext[1]}'


class User(AbstractUser):
    """Custom User Model inherited from Django's Abstract User model"""
    email = models.EmailField(
        _('email address'), unique=True)  # email is required

    image = models.ImageField(
        _('avatar'), upload_to=user_directory_path,
        blank=True, null=True,
        help_text=_('avatar AKA user image'))


class Group(DjangoBaseGroup):
    """Custom Group Model inherited from Django's default Group model"""

places/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from core.models import SeoBaseContentStampedModel, Item
from economics.models import Currency
from linguistics.models import Alphabet, Language


world_land_area = 149823000


class Place(SeoBaseContentStampedModel):
    """"""
    PLACE_TYPES = (
        ('WOR', _('World')),
        ('CON', _('Continent')),
        ('INT', _('International Region')),
        ('IOR', _('International Organization')),
        ('SGR', _('Statistical Group')),
        ('COU', _('Country')),
        ('SC1', _('SubCountry 1')),
        ('SC2', _('SubCountry 2')),
        ('SC3', _('SubCountry 3')),
        ('SC4', _('SubCountry 4')),
    )

    long_name = models.CharField(
        _('long name'), max_length=250, default='', blank=True)

    place_type = models.CharField(
        _('place type'), max_length=3, choices=PLACE_TYPES,
        db_index=True)

    geo_name_id = models.PositiveIntegerField(
        _('geo name id'), default=0, blank=True,
        help_text=_('from geonames.org'))

    latitude = models.FloatField(
        _('latitude'), blank=True, null=True,
        validators=[
            MinValueValidator(-90.0),
            MaxValueValidator(90.0)]
    )
    longitude = models.FloatField(
        _('longitude'), blank=True, null=True,
        validators=[
            MinValueValidator(-180.0),
            MaxValueValidator(180.0)]
    )

    coastline = models.PositiveIntegerField(
        _('coastline'), blank=True, null=True)
    width = models.PositiveIntegerField(
        _('width'), blank=True, null=True)
    length = models.PositiveIntegerField(
        _('length'), blank=True, null=True)

    water_area = models.FloatField(
        _('water area'), default=0.0, blank=True,
        help_text=_('km2'))
    land_area = models.FloatField(
        _('land area'), default=0.0, blank=True,
        help_text=_('km2'))
    area = models.FloatField(
        _('total area'), default=0.0, blank=True,
        help_text=_('km2'))

    def land_percent(self):
        if self.land_area + self.water_area:
            return self.land_area * 100 / (self.land_area + self.water_area)
        return 0.0
    land_percent.short_description = _('land area %')

    def water_percent(self):
        if self.land_area + self.water_area:
            return self.water_area * 100 / (self.land_area + self.water_area)
        return 0.0
    water_percent.short_description = _('water area %')

    def get_water_area(self):
        return intcomma(self.water_area)

    def get_land_area(self):
        return intcomma(self.land_area)

    def get_area(self):
        return intcomma(self.area)

    class Meta:
        abstract = True
        unique_together = ('name', 'place_type')

    def save(self, *args, **kwargs):

        if not self.area:
            self.area = self.land_area + self.water_area

        super().save(*args, **kwargs)


class World(Place):
    """"""
    item = GenericRelation(Item)

    class Meta:
        verbose_name = _('World')
        verbose_name_plural = _('World')
        ordering = ('id',)

    def get_absolute_url(self):
        return reverse('world-detail')


class Continent(Place):
    """"""
    item = GenericRelation(Item)

    class Meta:
        verbose_name = _('Continent')
        verbose_name_plural = _('Continents')
        ordering = ('id',)

    def get_absolute_url(self):
        return reverse('continent-detail', args=['self.slug'])


class Region(Place):
    """"""
    item = GenericRelation(Item)

    class Meta:
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')
        ordering = ('id',)

    def get_absolute_url(self):
        return reverse('region-detail', args=['self.slug'])


class Country(Place):
    """UN defined countries"""
    DRIVINGSIDES = (
        ('R', _('Right')), ('L', _('Left'))
    )
    DEPENDENCY_STATUS = (
        (0, _('dependent country')),
        (1, _('sovereign state')),
        (2, _('sovereign and disputed country')),
        (3, _('dependent and disputed area')),
        (4, _('geographical term')),
        (5, _('uninhabited area')),
    )

    long_name = models.CharField(
        _('official name'), max_length=250, default='', blank=True)
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='+', verbose_name=_('parent country'),
        help_text=_('this field is not null for dependent countries'))
    is_independent = models.SmallIntegerField(
        _('is independent'), editable=False,
        default=1, choices=DEPENDENCY_STATUS)
    is_alive = models.BooleanField(
        _('alive'), default=True)

    capital_text = models.CharField(
        _('capital'), max_length=250, default='', blank=True)

    iso_numeric = models.PositiveSmallIntegerField(
        _('ISO numeric'))
    iso2 = models.CharField(
        _('ISO2'), max_length=2, unique=True, db_index=True)
    iso3 = models.CharField(
        _('ISO3'), max_length=3, unique=True, db_index=True)
    # iso_3166_2 = models.CharField(
    #     _('ISO 3166-2'), max_length=25, unique=True)

    e164 = models.CharField(
        _('E164'), max_length=25, default='', blank=True)
    phone_code = models.CharField(
        _('phone code'), max_length=25)
    fips = models.CharField(
        _('FIPS'), max_length=25, default='', blank=True)
    tld = models.CharField(
        _('TLD'), max_length=5, default='', blank=True,
        help_text=_('Top Level Domain'))

    driving_side = models.CharField(
        _('driving side'), max_length=1,
        default='R', choices=DRIVINGSIDES)

    item = GenericRelation(Item)

    currencies = models.ManyToManyField(
        Currency, related_name='countries',
        through='places.CountryCurrency')
    languages = models.ManyToManyField(
        Language, related_name='countries',
        through='places.CountryLanguage')
    alphabets = models.ManyToManyField(
        Alphabet, related_name='countries',
        through='places.CountryAlphabet')

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')
        ordering = ('id',)

    def get_absolute_url(self):
        return reverse('country-detail', args=[self.slug])

    def save(self, *args, **kwargs):
        # self.is_independent = False if self.parent else True
        super().save(*args, **kwargs)

    @cached_property
    def area_rate(self):
        return (self.area / world_land_area) * 100


class CountryAlphabet(models.Model):
    """"""
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE,
        related_name='countryalphabets', verbose_name=_('country'))
    alphabet = models.ForeignKey(
        Alphabet, on_delete=models.CASCADE,
        related_name='countryalphabets', verbose_name=_('alphabet'))

    def __str__(self):
        return f'{self.country} - {self.alphabet}'


class CountryCurrency(models.Model):
    """"""
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE,
        related_name='countrycurrencies', verbose_name=_('country'))
    currency = models.ForeignKey(
        Currency, on_delete=models.CASCADE,
        related_name='countrycurrencies', verbose_name=_('currency'))

    def __str__(self):
        return f'{self.country} - {self.currency}'


class CountryLanguage(models.Model):
    """"""
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE,
        related_name='countrylanguages', verbose_name=_('country'))
    language = models.ForeignKey(
        Language, on_delete=models.CASCADE,
        related_name='countrylanguages', verbose_name=_('language'))
    is_official = models.BooleanField(
        _('is official'), default=True, blank=True)

    def __str__(self):
        return f'{self.country} - {self.language}'

places/views.py
import json

from django.db.models import Q, Prefetch
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from django.urls import resolve
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.defaults import server_error
from django.views.generic import DetailView, ListView, TemplateView

from core.choices import titles, current_year, current_year_gdp
from economics.models import Currency
from linguistics.models import Alphabet, Language
from stats.models import (
    CountryPopulation, WorldPopulation, CountryGdp, WorldGdp,
    Covid19)
from .models import Continent, Country, World


class CountryListView(ListView):
    """"""

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(is_alive=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = _('Countries')
        return context


class CountryDetailView(DetailView):
    """"""
    model = Country

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(is_alive=True).prefetch_related(
            Prefetch(
                'currencies',
                Currency.objects.only('name')),
            Prefetch(
                'languages',
                Language.objects.only('name')),
            Prefetch(
                'alphabets',
                Alphabet.objects.only('name')),
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.name
        context['title_page_prefix'] = _('Country')
        context['population'] = CountryPopulation.objects.filter(
            country__slug=self.kwargs['slug'], year=current_year).first()
        # context['gdp'] = CountryGdp.objects.filter(
        #     country__slug=self.kwargs['slug'], year=current_year_gdp).first()
        context['gdp'] = CountryGdp.objects.filter(
            country__slug=self.kwargs['slug']).order_by('-year').first()

        context['covid19'] = Covid19.objects.filter(
            country__slug=self.kwargs['slug']).order_by('-date').first()

        return context


class WorldDetailView(TemplateView):
    """"""

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = _('World')
        context['world'] = World.objects.all().first()
        context['population'] = WorldPopulation.objects.filter(
            year=current_year).first()
        context['gdp'] = WorldGdp.objects.filter(year=current_year_gdp).first()

        # latest_date = Covid19.objects.latest('date').date
        context['covid19'] = Covid19.objects.world().order_by('-date').first()
        return context


class ContinentListView(ListView):
    """"""
    model = Continent

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = _('Continents')
        return context


class ContinentDetailView(DetailView):
    """"""
    model = Continent

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.name
        context['title_page_prefix'] = _('Continent')
        return context

assets/templates/lte/places/base-list.html
{% extends 'lte/places/base.html' %}
{% load static i18n humanize %}

{% block extra_plugin_style %}

  {% include 'lte/_extra-plugin-css.html' %}

{% endblock %}

{% block content %}{% endblock %}

{% block extra_plugin_script %}

  {% include 'lte/_extra-plugin-js.html' %}

{% endblock %}

{% block extra_script %}
<script>
    $(function () {
      $('#list').DataTable({
        "paging": true,
        "pageLength": 100,
        "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
{% endblock %}

assets/templates/lte/places/country-detail.html
{% extends 'lte/places/base.html' %}
{% load static i18n humanize imagekit %}

{% block content %}
<div class="d-flex justify-content-center align-items-center">
  <div class="col-md-10 col-12">

    <div class="alert alert-info">
      <h5>
        <i class="icon fas fa-info"></i> 
        <strong>{{ object.name }}</strong> 
          {% if object.long_name %}
          (<em>{{ object.long_name }}</em>)
          {% endif %}
        is a {{ object.get_is_independent_display }}{% if not object.parent %}. 
      {% else %}
        and has dependency to 
        <a href="{% url 'country-detail' object.parent.slug %}">
          {{ object.parent }}</a>.{% endif %}
      </h5>

      <p>
        <a href="{% url 'capital-city-list' %}" 
          title="{% trans 'Capital cities in the world' %}">
          Capital city</a> of {{ object.name }} is <em>{{ object.capital_text }}</em>.
      </p>
    </div>

    {% if covid19.total_confirmed != 0 %}
    <a href="{% url 'country-covid19-detail' object.slug %}" 
          title="{{ object.name }} covid-19 statistics">
      <div class="small-box bg-danger">
        <div class="icon">
          <i class="fa fa-virus"></i>
        </div>
        <div class="inner">
          <h4 class="text-center">Covid 19 (coronavirus)</h4>
          <div class="row text-center">
            <div class="col-md-6 col-12">
              <h5>
                Total confirmed: {{ covid19.total_confirmed|intcomma }} <br>
                <small>
                  Today confirmed: {{ covid19.new_confirmed|intcomma }}
                </small>
              </h5>
            </div>
            <div class="col-md-6 col-12">
              <h5>
                Total deaths: {{ covid19.total_death|intcomma }} <br>
                <small>
                  Today deaths: {{ covid19.new_death|intcomma }}
                </small>
              </h5>
            </div>
          </div>
          <p class="text-center">
            For some countries data may shift for a day because date in 
            WHO Covid 19 data is the date of reporting to World Health 
            Organization.</p>
        </div>
        <span class="small-box-footer">
          ({{ covid19.source.code }}, {{ covid19.date }})
        </span>
      </div>
    </a>
    {% endif %}

    <div class="container row">

      <div class="col-md-6 col-12">

        {% if gdp %}
        <a href="{% url 'country-gdp-detail' object.slug %}" 
          title="{{ object.name }} GDP">
          <!-- small card -->
          <div class="small-box bg-success">
            <div class="inner">
              <h4 class="text-center">Gross Domestic Product (GDP)</h4>
              <h4>
                <strong>${{ gdp.gdp_current|intcomma }}</strong>
              </h4>
              <p>Gross Domestic Product (GDP): 
                ${{ gdp.gdp_current|intword }}</p>
              <h4>
                <strong>${{ gdp.gdp_percapita_current|intcomma }}</strong>
              </h4>
              <p>GDP per capita</p>
              
              {% if gdp_ppp_current %}
              <hr>
              <h4>
                <strong>${{ gdp.gdp_ppp_current|intcomma }}</strong>
              </h4>
              <p>GDP PPP: 
                ${{ gdp.gdp_ppp_current|intword }}
              </p>
              <h4>
                <strong>${{ gdp.gdp_percapita_ppp_current|intcomma }}</strong>
              </h4>
              <p>GDP PPP per capita</p>
              {% endif %}
            </div>
            <div class="icon">
              <i class="fas fa-money"></i>
            </div>
            <span class="small-box-footer">
              ({{ gdp.source.code }}, {{ gdp.year }})
            </span>
          </div>
        </a>
        {% endif %}

        {% if object.currencies %}
        <div class="info-box bg-info">         
          <span class="info-box-icon">
            <a href="{% url 'country-currency-list' %}"
              title="Country currencies">
              <i class="fa fa-credit-card"></i></a>
          </span>
        
          <div class="info-box-content">
            <span class="info-box-text">Currency: 
              <strong>
                {% for curr in object.currencies.all %}
                  {{ curr.name }} ({{ curr.iso3 }}){% if not forloop.last %},{% endif %}
                {% endfor %}
              </strong>
            </span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        {% endif %}

        <div class="info-box bg-success">
          <span class="info-box-icon">
            <a href="{% url 'phone-code-list' %}"
              title="International phone codes">
            <i class="fas fa-phone-alt"></i></a>
          </span>
      
          <div class="info-box-content">
            <span class="info-box-text">International phone code</span>
            <span class="info-box-number">{{ object.phone_code }}</span>
            {% if object.e164 %}
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              e164: <strong>{{ object.e164 }}</strong> 
            </span>
            {% endif %}
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->

        {% if object.tld %}
        <div class="info-box bg-info">
          <span class="info-box-icon">
            <a href="{% url 'country-tld-list' %}"
              title="Top level domains (TLDs)">
              <i class="fas fa-network-wired"></i></a>
          </span>
      
          <div class="info-box-content">
            <span class="info-box-text">Top level domain (tld)</span>
            <span class="info-box-number">
              .{{ object.tld }}</span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              This TLD is country specific 
              <br>
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        {% endif %}
          
        {% if object.iso2 and object.iso2|first not in '0123' %}
        <div class="info-box bg-success">         
          <span class="info-box-icon">
            <a href="{% url 'country-code-list' %}"
              title="Country codes (ISO, UN, FIPS)">
              <i class="fas fa-code"></i></a>
          </span>
        
          <div class="info-box-content">
            <span class="info-box-text">ISO 3166-2</span>
            <span class="info-box-number">{{ object.iso2 }}</span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              ISO 3166-3: <strong>{{ object.iso3 }}</strong> <br>
              ISO numeric code: <strong>{{ object.iso_numeric }}</strong> <br>
              FIPS code: <strong>{{ object.fips }}</strong> 
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        {% endif %}

        <div class="info-box bg-info">
          <span class="info-box-icon">
            <a href="{% url 'driving-side-list' %}"
              title="Country driving sides">
              <i class="fas fa-car"></i></a>
            </span>
      
          <div class="info-box-content">
            <span class="info-box-text">Driving side</span>
            <span class="info-box-number">
              {{ object.get_driving_side_display }}</span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              <br>
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
          
      </div>

      <div class="col-md-6 col-12">

        <a href="{% url 'country-population-detail' object.slug %}" 
          title="{{ object.name }} population">
          <!-- small card -->
          <div class="small-box bg-warning">
            <div class="inner">
              <h4 class="text-center">Population</h4>
              <h4>
                <strong>{{ population.total|intcomma }}</strong>
              </h4>
              <p>Population: {{ population.total|intword }}</p>
              <hr>
              {% if population.male %}
              <h5><strong>{{ population.male|intcomma }}</strong></h5> 
              <p>
                Male Population 
                ({{ population.male_percent|floatformat:1}} %)
              </p>
              {% endif %}
              {% if population.female %}
              <h5><strong>{{ population.female|intcomma }}</strong></h5>
              <p>
                Female Population 
                ({{ population.female_percent|floatformat:1}} %)</p>
              <hr>
              {% endif %}
              {% if population.change %}
              Population growth: <strong>
                {{ population.change|intcomma }} 
                ({{ population.change_rate|floatformat:2 }}%)
              </strong> <br> {% endif %}
              {% if population.median_age %}
              Median age: <strong>
                {{ population.median_age|floatformat:1 }} years</strong> <br> {% endif %}
              {% if population.density %}
              Density: <strong>
                {{ population.density|floatformat:1 }} people/km2</strong> <br> {% endif %}
              {% if population.fertility_rate %}
              Total Fertility: <strong>
                {{ population.fertility_rate|floatformat:1 }} 
              </strong> live births per woman <br> {% endif %}
            </div>
            <div class="icon float-left">
              <i class="fas fa-users"></i>
            </div>
            <span class="small-box-footer">
              ({{ population.source.code }}, {{ population.year }})
            </span>
          </div>
        </a>
        
        <div class="info-box bg-success">
          <span class="info-box-icon">
            <a href="{% url 'country-area-list' %}"
              title="Country areas">
              <i class="far fa-map"></i></a>
            </span>
      
          <div class="info-box-content">
            <span class="info-box-text">Surface area</span>
            <span class="info-box-number">
              {% if object.area < 50 %}
                {{ object.area|floatformat:2|intcomma }}
              {% else %}
                {{ object.area|floatformat:0|intcomma }}
              {% endif %}
              km2
            </span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              Land area: {% if object.land_area < 50 %}
                {{ object.land_area|floatformat:2|intcomma }}
              {% else %}
                {{ object.land_area|floatformat:0|intcomma }}
              {% endif %}
              km2 
              <span class="small">({{ object.land_percent|floatformat:1 }} %)</span>
              <br>
              Water area: {% if object.water_area < 50 %}
                {{ object.water_area|floatformat:2|intcomma }}
              {% else %}
                {{ object.water_area|floatformat:0|intcomma }}
              {% endif %}
              km2 
              <span class="small">({{ object.water_percent|floatformat:1 }} %)</span>
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->

        {% if object.latitude %}
        <div class="info-box bg-info">     
          <div class="info-box-content">
            <span class="progress-description">
              Coordinates: 
              <strong>  
                  {{ object.latitude }}
                  {% if object.latitude > 0 %} N {% else %} S{% endif %}
                  {{ object.longitude }}
                  {% if object.longitude > 0 %} E {% else %} W{% endif %}
              </strong>
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        {% endif %}
          
        {% if object.languages or object.alphabets %}
        <div class="info-box bg-warning">         
          <span class="info-box-icon">
            <a href="{% url 'country-language-list' %}"
              title="World languages and alphabets by countries">
              <i class="fas fa-language"></i></a>
          </span>
        
          <div class="info-box-content">
            <span class="info-box-text">Language(s): 
              <strong>
                {% for lang in object.languages.all %}
                  {{ lang }}{% if not forloop.last %},{% endif %}
                {% endfor %}
              </strong>
            </span>

            <span class="info-box-text">Alphabet(s): 
              <strong>
                {% for alp in object.alphabets.all %}
                  {{ alp }}{% if not forloop.last %},{% endif %}
                {% endfor %}
              </strong>
            </span>
      
            <div class="progress">
              <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
              * country's official language(s)
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        {% endif %}

      </div>

    </div>

  </div>
</div>
{% endblock content %}